### ISSUE TITLE
Feature request: Slow VFD scrolling

### ISSUE THREAD

**Issue by flottenheimer** [mv1f/pras3#1]
On A-P, meybarra said: "I added a line in the do_vfd function to slow the text scrolling". 
I'd love for that feature to be available in the executable. 

And thank you so much mv1f for all the work you've done on this gem of a P-ras app. Without those glorious lights, the P-ras just wouldn't look as incredible as it does. Much appreciated.

**Comment by mv1f** [comment]
No problem. I've written the code, I just haven't had time to test it. I'll try to test it this weekend.

**Comment by mv1f** [comment]
Added with c3ab571. It's in the latest release.
